version: '3'

services:
    web:
        image: nginx:1.25.4-alpine
        restart: always
        volumes:
            - ./:/app
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        ports:
            - "8081:80"

    redis:
        image: redis:7.2-alpine
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis:/root/redis
        environment:
            - REDIS_PASSWORD:${REDIS_PASSWORD}
            - REDIS_PORT:${REDIS_PORT}
            - REDIS_DATABASES:16

    php-fpm:
        build: ./docker/php-fpm
        restart: always
        depends_on:
            - db
        volumes:
            - .:/app

    db:
        image: postgres:16.2-alpine
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "6080:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}

volumes:
    redis:
        driver: local
    postgres:
        driver: local
